### ISSUE TITLE
Discussion on SBGP-0001: Stake Gauges

### ISSUE THREAD

**Issue by SolBlazeDev** [SolBlazeOrg/governance-proposals#2]
SolBlaze would like to propose a change to the BlazeStake standard delegation strategy where 10% of stake under this strategy would be controlled by a novel gauge-based voting system.

More details about this proposal can be found here: https://github.com/SolBlazeOrg/governance-proposals/blob/main/proposals/0001-stake-gauges.md

**Comment by SolBlazeDev** [comment]
This proposal has been submitted to the SolBlaze DAO for an on-chain vote: https://app.realms.today/dao/7vrFDrK9GRNX7YZXbo7N3kvta7Pbn6W1hCXQ6C7WBxG9/proposal/9fH8JjhoNbeRNSTsHatDw6rGq1BWVNPAz8Hwxkpd6W5n

**Comment by shela63** [comment]
I like the new proposals
